### ISSUE TITLE
Promise failure when a Bookmark doesn't have a Title

### ISSUE THREAD

**Issue by KnowledgeGarden** [topicquests/tqks-featherweight-prototype#118]
**Describe the bug**
Use the bookmark on a webpage -- e.g. a pdf file -- which doesn't have a title, and the system appears to freeze. Clicking Submit again does nothing. It's ok, but it fails. The fix is to type a title in that page.
We do have Title Validation on some pages, apparently not BookmarkForm.vue

**To Reproduce**
1. Go to http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.65.3502&rep=rep1&type=pdf
2. Click on the FeatherWeight Bookmarklet (typically a localhost for testing)
3. Scroll down to Submit and Click
4. See error -- the system does not show an error: you can see if in the javascript console if you "inspect" the page

**Expected behavior**
If all goes well, the system paints the new bookmark view

**Comment by KnowledgeGarden** [comment]
This is interesting: BookmarkForm.vue has a validate url and  validate title already installed. It would appear they are not working.

My suggestion is that every Form, including TopicEdit **must** validate Label

**Comment by jontiritilli** [comment]
fixed
