### ISSUE TITLE
Enhancement: Use Vue router links instead of a href tags

### ISSUE THREAD

**Issue by elog08** [topicquests/tqks-featherweight-prototype#57]
Do a search / replace on the source code for URLs using traditional anchor tags, and replace them with vue-router links.

**Comment by elog08** [comment]
Fixed. Please verify @qmeupscotty

**Comment by KnowledgeGarden** [comment]
There are some :href codes that live in odd places in vue templates which will not submit to swapping to <router-link references. An example starts at line 38 of QuestView.vue:
`
        <div class="columnx" style="text-align: center;">
          <img class="headerimage" src="statics/images/ibis/issue.png">Questions
          <a
            v-if="isAuthenticated"
            :href="`/nodeedit/question/${q.type}/${q.nodeId}/${q.label}`"
          >
          <img class="respond" src="statics/images/respond_sm.png">
          </a>
        </div>
`
