### ISSUE TITLE
Bug: Email Token Verification

### ISSUE THREAD

**Issue by qmeupscotty** [topicquests/tqks-featherweight-prototype#70]
**Actual** 

As a user, I should be able to register with my email address, receive a token link, click the token link, which should send me to the token verification page, and I should be able to sign into my new featherweight account.

**Expected**

As I user when I register for a featherweight account I receive email, but the access token is not clickable. I must then copy and paste the access token into the address bar manually to be taken to the token verification page before I can sign in to my new account.

**Comment by byroncoughlinSr** [comment]
This is not a bug. It is what happens when using Mailtrap. Link works when using other mail service such as gmail.

**Comment by qmeupscotty** [comment]
I was testing from a gmail account at the time, so I'm not sure why it was happening if that's the case. I just tried registering again under 3 different emails, but I didn't get an activation email for either, not even to the Spam folders.

**Comment by byroncoughlinSr** [comment]
Where were you looking to see the email verification?

**Comment by qmeupscotty** [comment]
Any folder it might've gone to, Promotions, Spam, Inbox, etc... I registered with 2 gmails and a yahoo. Are you able to register?
