### ISSUE TITLE
mailtrap.io is returning a bad url

### ISSUE THREAD

**Issue by KnowledgeGarden** [topicquests/tqks-featherweight-prototype#74]
**Describe the bug**
It is offering this url
http://localhost:8080/index.html#/token/verify/01b7235ebf8cd465c9f0327da163d9
but this is the one which works
http://localhost:8080/token/verify/01b7235ebf8cd465c9f0327da163d9

**To Reproduce**
Just Register a new user then look at the message at mailtrap.io

I suspect that while the site has been modified to drop the "index.html#" part, the mailer app was not tweaked to change that.

**Comment by KnowledgeGarden** [comment]
The bug is in /api/src/config/default.js

"baseURL": "http://localhost:8080/index.html#",
should read
"baseURL": "http://localhost:8080",

**Comment by elog08** [comment]
Cannot reproduce.
