### ISSUE TITLE
Styling - Register Form is too thin

### ISSUE THREAD

**Issue by MonkeyBizNuss** [topicquests/tqks-featherweight-prototype#78]
**Describe the bug**
The Register form is too small within the window. Please style for Mobile / Desktop viewports.

**To Reproduce**
1. Go to http://tqmaster.herokuapp.com/register

**Expected behavior**
Please style for Mobile / Desktop viewports.

**Screenshots**
see attached

![image](https://user-images.githubusercontent.com/47435993/53217407-b4108600-360c-11e9-8e4e-0c39132e3427.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JasonDreier** [comment]
There is a pull request to resolve.
