### ISSUE TITLE
Right drawer not displaying correctly

### ISSUE THREAD

**Issue by byroncoughlinSr** [topicquests/tqks-featherweight-prototype#96]
**Describe the bug**
Tree in right drawer only shows lines as indication of tree branch

After creating quests, questions, answers, etc. The branches should show the icon and label.

**Comment by KnowledgeGarden** [comment]
We are still observing this behavior online in the new K-Hubs

**Comment by KnowledgeGarden** [comment]
A suggestion was to put a **Dismiss** button right on the drawer.

**Comment by byroncoughlinSr** [comment]
I will start work on this today

**Comment by byroncoughlinSr** [comment]
this has been fixed
